/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompanygr.benspatrimoniais;

/**
 *
 * @author FormatMicro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mcadastramento = new javax.swing.JMenu();
        Msetor = new javax.swing.JMenuItem();
        Mgrupomaterial = new javax.swing.JMenuItem();
        Mmaterial = new javax.swing.JMenuItem();
        Musuario = new javax.swing.JMenuItem();
        Mmovimento = new javax.swing.JMenu();
        Mrelatorio = new javax.swing.JMenu();
        Msair = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mcadastramento.setText("CADASTRAMENTO");

        Msetor.setText("SETOR");
        Msetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsetorActionPerformed(evt);
            }
        });
        Mcadastramento.add(Msetor);

        Mgrupomaterial.setText("GRUPO MATERIAL");
        Mgrupomaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MgrupomaterialActionPerformed(evt);
            }
        });
        Mcadastramento.add(Mgrupomaterial);

        Mmaterial.setText("MATERIAL");
        Mmaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MmaterialActionPerformed(evt);
            }
        });
        Mcadastramento.add(Mmaterial);

        Musuario.setText("USUARIOS");
        Musuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusuarioActionPerformed(evt);
            }
        });
        Mcadastramento.add(Musuario);

        jMenuBar1.add(Mcadastramento);

        Mmovimento.setText("MOVIMENTO");
        jMenuBar1.add(Mmovimento);

        Mrelatorio.setText("RELATORIO");
        jMenuBar1.add(Mrelatorio);

        Msair.setText("SAIR");
        Msair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MsairActionPerformed(evt);
            }
        });
        jMenuBar1.add(Msair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MsetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsetorActionPerformed
        // TODO add your handling code here:
        Setor setorTela = new Setor();
        setorTela.setVisible(true);
    }//GEN-LAST:event_MsetorActionPerformed

    private void MsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MsairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MsairActionPerformed

    private void MgrupomaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MgrupomaterialActionPerformed
        // TODO add your handling code here:
        GrupoMaterial grupoMaterialTela = new GrupoMaterial();
        grupoMaterialTela.setVisible(true);
    }//GEN-LAST:event_MgrupomaterialActionPerformed

    private void MmaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MmaterialActionPerformed
        // TODO add your handling code here:
        CadastroMaterial cadMaterialTela = new CadastroMaterial();
        cadMaterialTela.setVisible(true);
    }//GEN-LAST:event_MmaterialActionPerformed

    private void MusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusuarioActionPerformed
        // TODO add your handling code here:
        usuariosCad usuariosCadastroTela = new usuariosCad();
        usuariosCadastroTela.setVisible(true);
    }//GEN-LAST:event_MusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Mcadastramento;
    private javax.swing.JMenuItem Mgrupomaterial;
    private javax.swing.JMenuItem Mmaterial;
    private javax.swing.JMenu Mmovimento;
    private javax.swing.JMenu Mrelatorio;
    private javax.swing.JMenu Msair;
    private javax.swing.JMenuItem Msetor;
    private javax.swing.JMenuItem Musuario;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
